### ISSUE TITLE
Lubricant 

### ISSUE THREAD

**Issue by snarkbe** [AxelFougues/Thermal-implant-reverse-engeneering#1]
https://github.com/AxelFougues/Thermal-implant-reverse-engeneering/blob/36317fffd6df549d8704c1b0b88a50f165a2974d/README.md?plain=1#L20

This is explained here : https://forum.dangerousthings.com/t/detached-nubbin/19138/4

**Comment by AxelFougues** [comment]
Note that in this case the implant is held by a dent in the needle
![PXL_20230701_052615800.jpg](https://github.com/AxelFougues/Thermal-implant-reverse-engeneering/assets/12610924/3919afa1-e305-4cab-8c38-1792c2232ba4)
